package examples

import "context"

// generated by cnf-gen
// DO NOT modify, overwrite when regenerate

type CNF_FUNC_CreatePod_INPUT struct {
	context context.Context
	podName string
}

type CNF_FUNC_CreatePod_OUTPUT struct {
	newPodName string
	err        error
}
